name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Executa a pipeline quando houver push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login no Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Definir nas GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Definir nas GitHub Secrets

      # Build da imagem Docker multi-stage
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-distroless:latest .

      # Push da imagem para o Docker Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-distroless:latest
